changed the structure of start

diff --git a/start b/start
--- a/start
+++ b/start
@@ -1,12 +1,3 @@
-stty -echo
-if ping -q -c 1 -W 1 google.com >/dev/null; then
-  stty echo
-  echo "Internet connected"
-else
-  stty echo
-  echo "Internet Not Found Please Connect to internet to run"
-  exit 1
-fi
 if command -v g++ &>/dev/null; then
     echo "g++ complier found"
 else
@@ -17,37 +8,37 @@ if command -v python3 &>/dev/null; then
     echo Python 3 is installed
     
     if python3 -c "import requests"&>/dev/null; then
-        echo "Python Library request Found"
+        echo "Python3 Library request Found"
     else
-        echo "Please Install requests Python Library"
+        echo "Please Install requests Python3 Library"
         exit 1
     fi
 
     if python3 -c "import smtplib"&>/dev/null; then
-        echo "Python Library smtplib Found"
+        echo "Python3 Library smtplib Found"
     else
-        echo "Please Install smtplib Python Library"
+        echo "Please3 Install smtplib Python3 Library"
         exit 1
     fi 
 
     if python3 -c "import ssl"&>/dev/null; then
-        echo "Python Library ssl Found"
+        echo "Python3 Library ssl Found"
     else
-        echo "Please Install ssl Python Library"
+        echo "Please3 Install ssl Python Library"
         exit 1
     fi  
 
     if python3 -c "import sys"&>/dev/null; then
-        echo "Python Library sys Found"
+        echo "Python3 Library sys Found"
     else
-        echo "Please Install sys Python Library"
+        echo "Please Install sys Python3 Library"
         exit 1
     fi 
 
     if python3 -c "import json"&>/dev/null; then
-        echo "Python Library json Found"
+        echo "Python3 Library json Found"
     else
-        echo "Please Install json Python Library"
+        echo "Please Install json Python3 Library"
         exit 1
     fi 
 
@@ -60,6 +51,13 @@ if command -v python3 &>/dev/null; then
     exit 1 
     fi
     
+    if ping -q -c 1 -W 1 google.com >/dev/null; then
+        echo "Internet connected"
+    else
+        echo "Internet Not Found Please Connect to internet to run"
+        exit 1
+    fi
+
     echo "Running Code"
     ./a.out
     
